AllCops:
  TargetRubyVersion: 2.3.6
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'
    - 'pug-bot.gemspec'
    - 'Rakefile'
    - 'bin/pug'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Style/Documentation:
  Exclude:
    - 'example/**/*.rb'
    - 'spec/**/*.rb'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
Style/MixinUsage:
  Exclude:
    - 'spec/**/*.rb'
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
